export const options = [
    { key: 'apple', text: 'Apple', value: 'appl', image: { avatar: true, src: '/images/stocks/AAPL.png' } },
    { key: 'amazon', text: 'Amazon', value: 'amzn', image: { avatar: true, src: '/images/stocks/AMZN.png' } },
    { key: 'tesla', text: 'Tesla', value: 'tsla', image: { avatar: true, src: '/images/stocks/TSLA.png' } },
    { key: 'microsoft', text: 'Microsoft', value: 'msft', image: { avatar: true, src: '/images/stocks/MSFT.png' } },
    { key: 'googleA', text: 'Alphabet Class A', value: 'googl', image: { avatar: true, src: '/images/stocks/GOOG.png' } },
    { key: 'googleC', text: 'Alphabet Class C', value: 'goog', image: { avatar: true, src: '/images/stocks/GOOG.png' } },
    { key: 'berkshire', text: 'Berkshire Hathaway', value: 'brk.b', image: { avatar: true, src: '/images/stocks/BRK.B.png' } },
    { key: 'unitedhealth', text: 'UnitedHealth Group', value: 'unh', image: { avatar: true, src: '/images/stocks/UNH.png' } },
    { key: 'johnson&johnson', text: 'Johnson & Johnson', value: 'jnj', image: { avatar: true, src: '/images/stocks/JNJ.png' } },
    { key: 'exxon', text: 'Exxon Mobil', value: 'xom', image: { avatar: true, src: '/images/stocks/XOM.png' } },
    { key: 'meta', text: 'Meta Platforms', value: 'meta', image: { avatar: true, src: '/images/stocks/FB.png' } },
    { key: 'nvidia', text: 'Nvidia', value: 'nvda', image: { avatar: true, src: '/images/stocks/NVDA.png' } },
    { key: 'amd', text: 'Advanced Micro Devices', value: 'amd', image: { avatar: true, src: '/images/stocks/AMD.png' } },
    { key: 'homedepot', text: 'Home Depot', value: 'hd', image: { avatar: true, src: '/images/stocks/HD.png' } },
    { key: 'visa', text: 'Visa Inc', value: 'v', image: { avatar: true, src: '/images/stocks/V.png' } },
    { key: 'chevron', text: 'Chevron Corporation', value: 'cvx', image: { avatar: true, src: '/images/stocks/CVX.png' } },
    { key: 'mastercard', text: 'Mastercard', value: 'ma', image: { avatar: true, src: '/images/stocks/MA.png' } },
    { key: 'pfizer', text: 'Pfizer Inc.', value: 'pfe', image: { avatar: true, src: '/images/stocks/PFE.png' } },
    { key: 'elililly', text: 'Eli Lilly and Company', value: 'lly', image: { avatar: true, src: '/images/stocks/LLY.png' } },
    { key: 'abbvie', text: 'AbbVie Inc', value: 'abbv', image: { avatar: true, src: '/images/stocks/ABBV.png' } },
    { key: 'coca-cola', text: 'Coca-Cola Company', value: 'ko', image: { avatar: true, src: '/images/stocks/KO.png' } },
    { key: 'pepsico', text: 'PepsiCo Inc', value: 'pep', image: { avatar: true, src: '/images/stocks/PEP.png' } },
    { key: 'thermofisher', text: 'Thermo Fisher Scientific Inc', value: 'tmo', image: { avatar: true, src: '/images/stocks/TMO.png' } },
    { key: 'merk', text: 'Merk & Co. Inc.', value: 'mrk', image: { avatar: true, src: '/images/stocks/MRK.png' } },
    { key: 'broadcom', text: 'Broadcom Inc', value: 'avgo', image: { avatar: true, src: '/images/stocks/AVGO.png' } },
    { key: 'waltdisney', text: 'Walt Disney Company', value: 'dis', image: { avatar: true, src: '/images/stocks/DIS.png' } },
    { key: 'cisco', text: 'Cisco Systems Inc', value: 'csco', image: { avatar: true, src: '/images/stocks/CSCO.png' } },
    { key: 'verizon', text: 'Verizon Communications', value: 'vz', image: { avatar: true, src: '/images/stocks/VZ.png' } },
    { key: 'capitalone', text: 'Capital One Financial', value: 'cof', image: { avatar: true, src: '/images/stocks/COF.png' } },
    { key: 'realtyincome', text: 'Realty Income Corporation', value: 'o', image: { avatar: true, src: '/images/stocks/O.png' } },
    { key: 'dollartree', text: 'Dollar Tree', value: 'dltr', image: { avatar: true, src: '/images/stocks/DLTR.png' } },
    { key: 'moderna', text: 'Moderna Inc', value: 'mrna', image: { avatar: true, src: '/images/stocks/MRNA.png' } },
    { key: 'fedex', text: 'FedEx Corporation', value: 'fdx', image: { avatar: true, src: '/images/stocks/FDX.png' } },
    { key: 'generalmotors', text: 'General Motors Company', value: 'gm', image: { avatar: true, src: '/images/stocks/GM.png' } },
    { key: 'boeing', text: 'Boeing  Company', value: 'ba', image: { avatar: true, src: '/images/stocks/BA.png' } },
    { key: 'jpmorgan', text: 'JPMorgan Chase & Co.', value: 'jpm', image: { avatar: true, src: '/images/stocks/JPM.png' } },
    { key: 'bankofamerica', text: 'Bank of America Corp', value: 'bac', image: { avatar: true, src: '/images/stocks/BAC.png' } },
    { key: 'costco', text: 'Costco Wholesale Corporation', value: 'cost', image: { avatar: true, src: '/images/stocks/COST.png' } },
    { key: 'adobe', text: 'Adobe Incorporated', value: 'adbe', image: { avatar: true, src: '/images/stocks/ADBE.png' } },
    { key: 'nextera', text: 'Next Era Energy', value: 'nee', image: { avatar: true, src: '/images/stocks/NEE.png' } },
    { key: 'wellsfargo', text: 'Wells Fargo & Company', value: 'wfc', image: { avatar: true, src: '/images/stocks/WFC.png' } },
    { key: 'nike', text: 'Nike Inc.', value: 'nke', image: { avatar: true, src: '/images/stocks/NKE.png' } },
    { key: 'oracle', text: 'Oracle Corporation', value: 'orcl', image: { avatar: true, src: '/images/stocks/ORCL.png' } },
    { key: 'goldmansachs', text: 'Goldman Sachs Group', value: 'gs', image: { avatar: true, src: '/images/stocks/GS.png' } },
    { key: 'paypal', text: 'PayPal Holdings Inc.', value: 'pypl', image: { avatar: true, src: '/images/stocks/PYPL.png' } },
    { key: 'lockheed', text: 'Lockheed Martin Corporation', value: 'lmt', image: { avatar: true, src: '/images/stocks/LMT.png' } }
]
